viz_stack:
  stage: test
  trigger:
    include:
      - local: .gitlab-ci.viz.yml
    strategy: depend
    
  # TEST: TO BE REMOVED BEFORE MERGE!!!
  rules:
  #  - if: $CI_MERGE_REQUEST_IID
    # run on default branch in order to upload coverage report
    - if: $CI_COMMIT_BRANCH == "BRAYNS_306_Migrate_CI_to_Gitlab"

hpc_stack:
  stage: test
  trigger:
    include:
      - local: .gitlab-ci.hpc-spack.yml
    strategy: depend
    
  # TEST: TO BE REMOVED BEFORE MERGE!!!
  rules:
  #  - if: $CI_MERGE_REQUEST_IID
    # run on default branch in order to upload coverage report
    - if: $CI_COMMIT_BRANCH == "BRAYNS_306_Migrate_CI_to_Gitlab"

