viz_stack:
  stage: test
  trigger:
    include:
      - local: .gitlab-ci.viz.yml
    strategy: depend

hpc_stack:
  stage: test
  trigger:
    include:
      - local: .gitlab-ci.hpc-spack.yml
    strategy: depend

