viz_stack:
  stage: test
  trigger:
    include:
      - local: .gitlab-ci.viz.yml
    strategy: depend
    
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

hpc_stack:
  stage: test
  trigger:
    include:
      - local: .gitlab-ci.hpc-spack.yml
    strategy: depend
    
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

