name: Linter

on:
  pull_request:
    branches:
      - develop

jobs:
  clang-format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run clang-format
        run: |
          apt-get update

          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          ./llvm.sh 20

          apt-get install clang-format-20
          apt-get install clang-tidy-20

          SOURCES=$(find apps src tests \( -name "*.h" -or -name "*.cpp" \))
          clang-format-20 --dry-run --Werror $SOURCES
