name: Linter

on:
  pull_request:
    branches:
      - develop

jobs:
  clang-format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run clang-format
        run: |
          apt-get update

          wget https://apt.llvm.org/llvm.sh
          sudo chmod +x llvm.sh
          sudo ./llvm.sh 20
