name: Linter

on:
  pull_request:
    branches:
      - develop

jobs:
  clang-format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run clang-format
        run: |
          apt update
          bash scripts/install_llvm.sh
          SOURCES=$(find apps src tests \( -name "*.h" -or -name "*.cpp" \))
          clang-format-20 --dry-run --Werror $SOURCES
